### ISSUE TITLE
What is the reason to not support this module for V5?

### ISSUE THREAD

**Issue by nicolas-cusan** [dnadesign/silverstripe-elemental-subsites#15]
This is just a question as I am planning to build a page using elemental and Subsites. 

Is the functionality provided no longer needed? Is it in the core Elemental module?

Thank you for a quick reply!

Best regards

**Comment by ChloeSartorelli** [comment]
This module is not required for `dnadesign/silverstripe-elemental` to work with `silverstripe/subsites` - they should be compatible out of the box.

**Comment by nicolas-cusan** [comment]
Hello @GuySartorelli thank you for your answer.
