### ISSUE TITLE
Use DataObjectSchema to retrieve BaseElement table name

### ISSUE THREAD

**Issue by robbieaverill** [dnadesign/silverstripe-elemental-subsites#2]
See https://github.com/dnadesign/silverstripe-elemental-subsites/commit/09844fe54f869a012dd8313202878fa4a8e00faf#diff-98d52a2200c54cbd348bf75d5b917e56R37

We should use `DataObject::getSchema()->tableName(BaseElement::class)` instead of embedding Element directly.

**Comment by raissanorth** [comment]
PR at https://github.com/dnadesign/silverstripe-elemental-subsites/pull/6
